### ISSUE TITLE
Rwhtml syntax: remove colon from directives

### ISSUE THREAD

**Issue by jechtom** [riganti/redwood#12]
```
@viewmodel: Redwood.Samples.BasicSamples.ViewModels.Sample2ViewModel, Redwood.Samples.BasicSamples
```
Should be:
```
@viewmodel Redwood.Samples.BasicSamples.ViewModels.Sample2ViewModel, Redwood.Samples.BasicSamples
```
Please update parser and samples.

**Comment by tomasherceg** [comment]
In that case we should also remove the colon from bindings so we are consistent accross the whole framework.
Personally I like the syntax with colon more and it is also used also in Knockout, CSS or JSON - people are used to it.

**Comment by exyi** [comment]
I also like the syntax with colon - the value is separated from key so it looks much cleaner what it is doing.

**Comment by jechtom** [comment]
This will confuse anyone who have ever used Razor where directives are defined same but without colon. And there are lot of people who are using .NET and Razor.

It is just useless symbol in syntax and another way how to define directives. 

Also directives and binding are not the same and I don't see why not having colon in directive should confuse developers with binding.

What do you think?

**Comment by tomasherceg** [comment]
Yesterday I talked with @ridercz that we might use completely different syntax for directives because rwhtml is not valid xml/html because of them. 
But for now I have removed the colons. 5c5ba8df
