### ISSUE TITLE
Rwhtml syntax: Binding should use only one curly brace

### ISSUE THREAD

**Issue by jechtom** [riganti/redwood#13]
Currently rwhtml is using single curly brace in attribute binding and double in HTML element content, like: `<p class="{value: Result}">{{value: Result}}<p>`. 
We should use single brace everywhere. For example:
`<p class="{value: Result}">{value: Result}<p>`. 

You should be able to escape opening binding with two opening curly braces.

**Comment by tomasherceg** [comment]
The double curly braces were chosen because of possible mismatch in <style> and <script> elements, e.g. <script>var a = {{value: MyProperty}};</script>
