### ISSUE TITLE
Event Validation - CommandResolver security

### ISSUE THREAD

**Issue by exyi** [riganti/redwood#18]
I have found critical security bug in CommandResolver.
Open 'Sample 6 - ViewModel property encryption and protection' and run this in developer console
```javascript
redwood.postBack('root', document, [], 'set_ReadOnlyData(SecretData)', '')
```
and see what is in protected data in viewmodel. This invocation has modified readonly data and read secret data.
I think we should read all binding before sending to client and then accept only these registered binding expressions. I hope this will help. We can also cache parsed binding expression to improve performance.

**Comment by tomasherceg** [comment]
Even if the property was not protected, it shouldn't be possible to call setter of a ViewModel property.
Fixed.

**Comment by exyi** [comment]
Still you can pass secret data to method as argument if some method will accept string. I some will accept byte or byte array you can pass key to it. I think adversary has too much power when it is possible to pass any (valid for this) expression to be evaluated.
If we would allow only registered expression, we can also give it more power. Power only to webmaster, not adversary.

**Comment by tomasherceg** [comment]
We should implement somethink like Event Validation in WebForms. 
Before command is executed, we need to verify that the binding with the expression exists on the command path. 
And maybe we should also check whether the control is enabled and visible - but this must be optional.

**Comment by ridercz** [comment]
Would not be easier to call only ViewModel methods marked with special attribute? Event validation in Web Forms fashion is road to hell.

**Comment by tomasherceg** [comment]
We only allow to call public methods on viewmodel, however it might be unsafe to allow the user to call any method with any parameter. 
The implementation of the event validation will be different - we don't need to put anything in the client's viewmodel, just before executing the command we'll check whether appropriate binding with same expression and path exists in the control tree. 
And also if the control's enabled or visible property evaluates to false, we'll deny the command, but it will possible to disable this behavior (setting a property on the control).

**Comment by exyi** [comment]
Meybe we can simply save the expression in internal storage and render only its id. Then client would be able to call only expressions stored on server.
After that we may do some extra validation

**Comment by tomasherceg** [comment]
I thought so too, however assigning an identifier to bindings is quite tricky. When the application restarts, or when it runs on multiple servers, the same binding must have the same id. The only way would be to create a hash of the expression and there can be bindings with same expression used in different areas of the page.
Moreover in future we want to translate some commands from C# to javascript and we'll need the function name and its parameters on the client side, so I don't think ids solve our problem. 

I'll implement a check that will go over the control tree and finds all command bindings and compare the expression and the path. That will be sufficient for now and it should be quite easy.
