### ISSUE TITLE
Security bug in deserialization of protected values

### ISSUE THREAD

**Issue by exyi** [riganti/redwood#22]
When deserializing there is no control if object in array I really belongs to this property.
In the 'Sample 6 - ViewModel property encryption and protection' first remove explicit proteced data validation (method ValidateSecretDataDecryptedSuccessfully). Then you can run this command in developer console to display SecretData property.
```
redwood.viewModels.root.ReadOnlyData$encrypted(redwood.viewModels.root.SecretData$encrypted())
```

**Comment by tomasherceg** [comment]
Good catch. I have modified the converter to serialize and deserialize the properties always in the alphabetical order, so we don't need to store indexes in the object, because the order of properties is always the same.

**Comment by exyi** [comment]
Oh, nice idea
