### ISSUE TITLE
Authorization and action filters

### ISSUE THREAD

**Issue by tomasherceg** [riganti/redwood#23]
Implement the action filtering mechanism similar to ASP.NET Web API and MVC. The filters can be applied:
- on the method level
- on the viewmodel level
- globally

Then implement the Authorize attribute (which is an action filter) and a RedirectToLoginPageAttribute that redirects to a specified URL when an UnauthorizedAccessException occurs.

**Comment by ridercz** [comment]
RedirectToLoginPageAttribute expects some kind of forms auth-like authentication, which may not be true. Just set HTTP status 401 and leave on authentication middleware how to deal with that.

**Comment by tomasherceg** [comment]
Is there some existing Owin authentication middleware for forms-like authentication?

**Comment by jechtom** [comment]
Yes, its called CookieAuthentication

**Comment by tomasherceg** [comment]
OK, so the RedirectToLoginPageAttribute is not needed.
