### ISSUE TITLE
Ugly markup in  rwhtml with dark theme

### ISSUE THREAD

**Issue by martinsura** [riganti/redwood#55]
Rwhtml is ugly in Dark theme

I am using Visual Studio CTP 6 and Redwood extension 0.5

Intellisense  is fine.

![rwhtml](https://cloud.githubusercontent.com/assets/333932/6966398/0cd76750-d959-11e4-8574-82e65e091976.png)

**Comment by tomasherceg** [comment]
For now you can change the colors in the Options dialog.
In the next version of the extension, we'll have some nice default colors for dark theme.
