### ISSUE TITLE
List NuGet Package Manager for Visual Studio 2015 as a dependency for the VS extension

### ISSUE THREAD

**Issue by TomasHubelbauer** [riganti/redwood#61]
This might be a fault on my part, but my attempt to install the Visual Studio extension for Redwood development failed on an unresolved dependency: *[NuGet Package Manager for Visual Studio 2015](https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d)*.

The extension does list the Nuget PM dependency in its manifest file, so it seems to be an issue with Visual Studio, some former CTP might have not bundled the Nuget PM extension with itself or my install was just faulty. It's true that my CPT install mostly gathered dust for some weeks, so this might not be an issue with newer CTPs, but it was a vanilla install, not modified in any case after the initial install.

In any case, manual installation of the dependency was required for me to be able to install the extension, so this might be worthy of linking as a known issue considering the fact VS fails to download and offer the dependency even though the dep ID is in the manifest.

**Comment by tomasherceg** [comment]
I am aware of the issue and it is described in Wiki.
The workaround is to update the Nuget extension or uninstall it and install it again.
It happens only sometimes in Visual Studio 2015 CTP 6.

**Comment by TomasHubelbauer** [comment]
Can you link me to the mention in the Wiki? I can't seem to find it anywhere and I followed the *How to Start* article, which doesn't seem to mention it.

**Comment by tomasherceg** [comment]
Oh, my mistake - I have edited the page recently and probably removed the paragraph. It is back again on the How to start page.

**Comment by tomasherceg** [comment]
Tested in the Visual Studio 2015 RC and it works. Can someone else build the extension from the master branch and confirm that it works and there is no problem with NuGet Package Manager extension?

**Comment by TomasHubelbauer** [comment]
I'll try it out tomorrow and let you know.

**Comment by martinsura** [comment]
Still bugged for me. Build and install with no problem, but only rw: controls works. External controls defined in redwood.json not work and format document (ctrl+k d) not working again.

**Comment by tomasherceg** [comment]
Can you try this build? http://riganti.cz/download/Redwood.VS2015Extension_v0.6.zip

**Comment by martinsura** [comment]
Still not working both. Maybe problem with some extensions? I am using (EditorConfig -> btw still not working and Web Essential 2015 RC)

**Comment by tomasherceg** [comment]
We have found the problem and fixed it. The logging to the VS extension was added.
