### ISSUE TITLE
Date format string in GridView control not working in SPA mode

### ISSUE THREAD

**Issue by martinsura** [riganti/redwood#70]
Datetime property and SPA mode
```
<rw:GridViewTextColumn AllowSorting="true" ValueBinding="{value: Created}" FormatString="dd. MMMM yyyy" HeaderText="Vytvořen" />
```
Framework returns javascript error "Cannot read property 'calendar' of null"

**Comment by tomasherceg** [comment]
After further investigation I have found that this happens when the page in SPA needs some extra resources (e.g. scripts with globalization code). Those are not fetched on postback.

**Comment by exyi** [comment]
It should load these resources correctly in current version.
