### ISSUE TITLE
RouteLink control binding in Repeater not working

### ISSUE THREAD

**Issue by martinsura** [riganti/redwood#77]
```
<rw:Repeater DataSource="{value: Navigation}" WrapperTagName="ul" class="nav navbar-nav">
  <ItemTemplate>
     <li class='{value: IsActive == true ? "active" : "" }'>
        <rw:TextBox Text="{value:RouteName}" />
        <rw:RouteLink RouteName="{value: RouteName}" Text="Test"  />
     </li>
  </ItemTemplate>
</rw:Repeater>
```
TextBox binding work, but  RouteLink binding not. Routelink trageting wrong model. (page instead datasrouce)

**Comment by tomasherceg** [comment]
Try adding RenderSettings.Mode="Server" on the Repeater, it should work.
The RouteName property can be data-bound but only in the server rendering mode as the route table is not available on the client.

**Comment by martinsura** [comment]
Nice, it works :) Thanks for help.

**Comment by lucwuyts** [comment]
It doesn't work in  RenderSettings.Mode="Server" on the Repeater
This is with version   1.1.8.2

**Comment by exyi** [comment]
@luboshl You should now use `resource` binding if you want to bind RouteName property. Note that it will never refresh after it's rendered.

**Comment by lucwuyts** [comment]
Yes, working perfectly.  Thanks.
I did not find the possibility for resource binding to bind with properties in the docs.  (or i did not look hard enough)
