### ISSUE TITLE
Support for Virtual directory on IIS Application

### ISSUE THREAD

**Issue by holajan** [riganti/redwood#85]
Hosting application on IIS Application in Virtual directory in Site when URL is someting like 'http://localhost/MyApplication' is now not supported by Redwood.
Problem is in ResourceBase and JQueryGlobalizeCultureMiddleware class when resources URL is now for root only (/redwoodEmbeddedResource?name=.. instead of /MyApplication/redwoodEmbeddedResource?name=).

In OWIN based application can be base URL obtained by this code:
string requestPathBase = (string)context.Request.Environment["owin.RequestPathBase"];
and in ASP.NET 5 with:
string requestPathBase = context.Request.PathBase.Value;

**Comment by holajan** [comment]
If there will be Virtual directory support, then I would like to add support for tilde URLs ("~/") for "href" and "src" attributes on Redwood controls like in MVC.

This could be do something like this:
In HtmlGenericControl.AddAttributesToRender:
// render hard-coded HTML attributes
foreach (var attribute in Attributes.Where(a => a.Value is string))
{
    string value = attribute.Value.ToString();
    if ((attribute.Key.Equals("href", StringComparison.OrdinalIgnoreCase) || attribute.Key.Equals("src", StringComparison.OrdinalIgnoreCase)) &&
        value.StartsWith("~/"))
    {
        //Convert App Relative URL to relative URL
        value = Utils.VirtualPathUtils.ResolveRelativeUrl(context.RequestContext.OwinContext, value);
    }

    writer.AddAttribute(attribute.Key, value, true);
}

and add VirtualPathUtils helper class:
internal class VirtualPathUtils
{
    public static string ResolveRelativeUrl(IOwinContext /*Context*/ context, string appRelativeUrl)
    {
        if (!appRelativeUrl.StartsWith("~/"))
        {
            throw new ArgumentException("Invalid app relative URL.", nameof(appRelativeUrl));
        }

        string requestPathBase = (string)context.Request.Environment["owin.RequestPathBase"];
        //string requestPathBase = context.Request.PathBase.Value;
        return requestPathBase + appRelativeUrl.Substring(1);
    }
}

**Comment by tomasherceg** [comment]
I have fixed the design of virtual directories, now they should work. 

There is also a new method TranslateVirtualPath in RedwoodRequestContext class, that does the same thing as ResolveClientUrl in WebForms - translates ~/path to /virtDir/path when the app runs in the virtual directory. It is supported everywhere, including Redirect method or SPAs.

Also the a[href], img[src] and other attributes now support virtual paths. I have created an extensibility point for this - in the configuration.Markup.HtmlAttributeTransforms you can specify custom transform and apply it globally on particular HTML attribute. You can change the way how the specific attribute is rendered.

**Comment by holajan** [comment]
Seems that it working fine, thanks
